# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: tsconfig
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: .gitignore
      # TODO: enable this
      # - id: no-commit-to-branch
      #   args:
      #     - --branch main
      - id: trailing-whitespace
        exclude: .gitignore

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.0
    hooks:
      - id: editorconfig-checker
        exclude: |
            (?x)(
                \.gitignore$|
                \.sql\.go$|
            )

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.1
    hooks:
      - id: check-json5

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.8.0
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        language: system
        entry: 'go mod tidy'
        files: ^go.(mod|sum)|.+\.go$
        pass_filenames: false

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.14 # Use the sha / tag you want to point at
    hooks:
      - id: biome-check

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.0.1
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix

  - repo: local
    hooks:
      - id: sqlc-generate
        name: sqlc generate
        entry: sqlc generate
        language: system
        # Rerun the hook if the configuration or SQL queries change
        files: |
            (?x)^(
                sqlc\.yaml|
                \.sqlc\.yaml|
                \.sqlc\.toml|
                \.sqlcignore|
                queries/.*\.sql|
                schema/.*\.sql
            )$
        pass_filenames: false
        # Ensure generated files are staged
        always_run: true

      - id: sqlc-vet
        name: sqlc vet
        entry: sqlc vet
        language: system
        files: '\.(sql|yaml)$'
        pass_filenames: false

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
