[tools]
"github:golang-migrate/migrate" = "4.19.1"
go = "1.25.6"
golangci-lint = "2.8.0"
node = "25.6.0"
"pipx:sqlfluff" = "4.0.0"
pre-commit = "4.5.1"

[tasks."sqlite:newMigration"]
description = "Generates a new migration for SQLite"
usage = """
arg "<name>" help="Name of the new migration"
"""
run = "migrate create --ext=sql --dir=database/sqlite/migrations --format=unix {{usage.name}}"
